### ISSUE TITLE
update() method doesn't allow to update a map field with some characters

### ISSUE THREAD

**Issue by juanleondev** [invertase/dart_firebase_admin#5]
## Steps to reproduce

1. Run the following
```
firestore.collection('yourCollection').doc('yourDoc')
     .update({'a.' : 'b'});
```

2. See the error 

`ArgumentError (Invalid argument (path): must not start or end with "." ...`

If we try to do it in the console it allows us to do that, so I guess it is not the correct behavior for a map field

Path: dart_firebase_admin-0.0.2/lib/src/google_cloud_firestore/path.dart

![image](https://github.com/invertase/dart_firebase_admin/assets/8674244/444e7830-087e-418a-9ee9-4cd287f05e88)

**Comment by rrousselGit** [comment]
That is expected. The console is unique in that regard
This is due to dots conflicting with the "field path" feature

If you do `update({"a.b": 42})`
This will not set doc["a.b"] but rather doc["a"]["b"]


The workaround is:
`update({FieldPath("a.b"): 42})`

That is consistent with how the Admin sdk works in Javascript

**Comment by juanleondev** [comment]
Thanks! @rrousselGit
